# Generated by Django 4.0.5 on 2022-07-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_author_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(default=None),
        ),
    ]
