# Generated by Django 4.0.5 on 2022-07-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_author_date_of_death'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books_list',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='books_list',
        ),
        migrations.AddField(
            model_name='book',
            name='author_list',
            field=models.ManyToManyField(to='catalog.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre_list',
            field=models.ManyToManyField(to='catalog.genre'),
        ),
    ]
