# Generated by Django 4.0.5 on 2022-07-02 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_author_options_alter_bookinstance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
    ]
