# Generated by Django 4.0.5 on 2022-07-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_book_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_list',
            new_name='author',
        ),
    ]
