# Generated by Django 4.0.5 on 2022-07-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_author_list_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors_list',
        ),
    ]
