# Generated by Django 4.0.5 on 2022-07-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
