# Generated by Django 4.0.5 on 2022-07-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_bookinstance_borrowed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_make_returned', 'Set book as returned'),)},
        ),
    ]
