# Generated by Django 4.0.5 on 2022-07-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_crud_author', 'Can C.R.U.D for Authors'),)},
        ),
    ]
