# Generated by Django 4.0.5 on 2022-07-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_crud', 'Can C.R.U.D for Authors'),)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['tittle'], 'permissions': (('can_crud', 'Can C.R.U.D for Books'),)},
        ),
    ]
